### ISSUE TITLE
Incorrect `org.osgi.service.prefs` dependency in org.eclipse.equinox.preferences-3.10.0

### ISSUE THREAD

**Issue by JohnLBergqvist** [eclipse-equinox/equinox.bundles#54] opened 2022-06-14 21:48 UTC
The declaration for the `org.osgi.service.prefs` dependency inside https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.preferences/3.10.0/org.eclipse.equinox.preferences-3.10.0.pom

is wrong. Instead of being:

```
    <dependency>
      <groupId>org.osgi.service</groupId>
      <artifactId>org.osgi.service.prefs</artifactId>
      <version>[1.1.0,1.2.0)</version>
    </dependency>
```

as it currently is, it should be

```
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.prefs</artifactId>
      <version>[1.1.0,1.2.0)</version>
    </dependency>
```
(basically, the `<groupId>` is wrong)
as can be seen on Maven Central: https://search.maven.org/artifact/org.osgi/org.osgi.service.prefs/1.1.2/jar

Otherwise, I get a 
```
org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 -> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0): No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range
```
error. If I patch the POM file in my local maven cache, this problem is resolved and the dependency downloads as expected.

**Comment by HannesWell** [comment] 2022-06-14 22:55
Thank you for your report.
The pom-file is generated during the release process (at least org.eclipse.equinox.preferences has none in git) and it looks like this generation is flawed.
@akurtakov or @mickaelistria can you help here or know who can do better?

**Comment by Fubuchi** [comment] 2022-06-15 04:40
We has the same issue today, the whole CI pipeline is broken because the group Id isn't existed. The current workaround is creating the folder structure as same as the wrong group Id and throwing the jar to there.

**Comment by akurtakov** [comment] 2022-06-15 05:04
@sravanlakkimsetti You're the best person to help here.

**Comment by cdietrich** [comment] 2022-06-15 05:50
i also wonder if we can create a new repo in eclipses nexus where some milestones or nightlies for these and also platform and jdt maven artifacts can be published. e.g. xtext could use these in their integ tests so that problems like this one are detected earlier

**Comment by laeubi** [comment] 2022-06-15 05:54
> i also wonder if we can create a new repo in eclipses nexus 

Why a new repo? Is the existing one not sufficient?

> where some milestones or nightlies for these and also platform and jdt maven artifacts can be published. e.g. xtext could use these in their integ tests so that problems like this one are detected earlier

The problem is that current maven deployment is a nasty script witch need manual execution... One the equinox repos are merged I plan to try setup a more automated flow for the equinox that could be used as a basis for other repos as well.

**Comment by cdietrich** [comment] 2022-06-15 05:56
when broken milestones are published to a release repo, then of course the "maven central" is broken problem would turn into the "eclipse release repo is broken"

**Comment by laeubi** [comment] 2022-06-15 06:01
At least in tycho, staging or milestone repos has been proven to produce more hassle than they solve.

If we publish something "broken" we simply should fix that and publish a new version immediately.

**Comment by akurtakov** [comment] 2022-06-15 06:01
repo.eclipse.org can be used to deploy SNAPSHOT versions and only builds that explicitly enable it will use them. We do that with Tycho and it works well sothere is no need for new repo. 
It's entirely separate question the effort to setup/automate that publishiing .

**Comment by sravanlakkimsetti** [comment] 2022-06-15 06:15
I am trying a solution for this one. It will take some time. but hopefully by today or tomorrow I will be able to fix this one

**Comment by castielfang** [comment] 2022-06-15 06:16
firstly maybe you should remove the version 3.10.0 from repository,stop  to effect the more users

**Comment by akurtakov** [comment] 2022-06-15 06:18
Can you actually remove things from Maven Central? I thought this is a not allowed.

**Comment by laeubi** [comment] 2022-06-15 06:22
> Can you actually remove things from Maven Central? I thought this is a not allowed.

https://stackoverflow.com/questions/9789611/removing-an-artifact-from-maven-central

You can only contact the support, but as no one is **forced** to upgrade their pom, you can simply use the old version in the meanwhile...

**Comment by kesslerd** [comment] 2022-06-15 06:28
> > Can you actually remove things from Maven Central? I thought this is a not allowed.
> 
> https://stackoverflow.com/questions/9789611/removing-an-artifact-from-maven-central
> 
> You can only contact the support, but as no one is **forced** to upgrade their pom, you can simply use the old version in the meanwhile...

I have a transitive dependency on this library and the version I used for the main library is fixed. However, the dependency specifies a range of allowed version and the latest will be used. So I was **forced** to add a gradle dependency constraint 

```
    constraints {
        implementation('org.eclipse.platform:org.eclipse.equinox.preferences:3.9.0') {
            force true
            because "Transitive dependency of org.eclipse.jdt:org.eclipse.jdt.core:3.17.0 newer version of org.eclipse.equinox.preferences points to wrong org.osgi location"
        }
    }
```

**Comment by JohnLBergqvist** [comment] 2022-06-15 06:29
> > Can you actually remove things from Maven Central? I thought this is a not allowed.
> 
> https://stackoverflow.com/questions/9789611/removing-an-artifact-from-maven-central
> 
> You can only contact the support, but as no one is **forced** to upgrade their pom, you can simply use the old version in the meanwhile...

I also have a transitive dependency which is bringing this in.

**Comment by laeubi** [comment] 2022-06-15 06:37
> I have a transitive dependency on this library and the version I used for the main library is fixed. However, the dependency specifies a range of allowed version and the latest will be used. So I was **forced** to add a gradle dependency constraint

Well that's what these features are for... you probably then should better blame the dependency specifying a version range without actually testing that the range is satiable...

**Comment by kailbin** [comment] 2022-06-15 06:43
> We have the same issue today, the whole CI pipeline is broken because the group Id isn't existed. The current workaround is creating the folder structure as same as the wrong group Id and throwing the jar to there.

So Do We ！！

**Comment by cdietrich** [comment] 2022-06-15 07:00
@laeubi  all of eclipse platform and also emf have "ranges of death"
e.g. from org.eclipse.core.runtime
https://search.maven.org/artifact/org.eclipse.platform/org.eclipse.core.runtime/3.25.0/jar

```
    <dependency>
      <groupId>org.eclipse.platform</groupId>
      <artifactId>org.eclipse.equinox.preferences</artifactId>
      <version>[3.10.0,4.0.0)</version>
    </dependency>
```

this leads to always new transitive stuff beeing pulled

**Comment by mcollovati** [comment] 2022-06-15 09:15
Can artifact relocation help in this case?
https://maven.apache.org/guides/mini/guide-relocation.html

**Comment by PranavPurwar** [comment] 2022-06-15 09:34
Any updates on when this (fixed) version would be released?

**Comment by akurtakov** [comment] 2022-06-15 09:37
As fast as we can - hopefully, today.

**Closed** 2022-06-15 11:05 UTC

**Comment by PranavPurwar** [comment] 2022-06-15 11:15
A Huge Thanks

**Comment by sravanlakkimsetti** [comment] 2022-06-15 11:25
its available in maven central now https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.preferences/3.10.1/

**Comment by Artur-** [comment] 2022-06-15 13:01
Sorry if I am just adding noise here but I would like to understand if this is supposed to work now. 

If I create a pom.xml with a dependency on `org.eclipse.platform`/`org.eclipse.core.runtime`/`3.25.0` and nothing else then running `mvn dependency:tree` will fail with
```
Failed to collect dependencies at org.eclipse.platform:org.eclipse.core.runtime:jar:3.25.0 -> org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 -> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0): No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range -> [Help 1]
```

So even if `org.eclipse.platform:org.eclipse.equinox.preferences:jar` 3.10.1 is out, the range of `[3.10.0,4.0.0)` in `platform:org.eclipse.core.runtime` is resolved to 3.10.0 and not 3.10.1 (Maven happily downloads both to the local .m2 cache but still wants to use 3.10.0)

Because of this, projects are still broken

Example pom here https://gist.github.com/Artur-/e71a91b5b6acedce37e0b8426b7cdcca

**Comment by PranavPurwar** [comment] 2022-06-15 13:05
You need to add equinox preferences as a separate dependency to maven/gradle for the changes to work currently.

**Comment by cdietrich** [comment] 2022-06-15 13:07
but should maven pull the newer preference version?
    <dependency>
      <groupId>org.eclipse.platform</groupId>
      <artifactId>org.eclipse.equinox.preferences</artifactId>
      <version>[3.10.0,4.0.0)</version>
    </dependency>
automatically? why does it still pick the old one?

**Comment by stephan-herrmann** [comment] 2022-06-15 13:14
In previous situations I observed that Maven explores the entire tree of possible dependencies, i.e., all allowed versions. If one of them fails resolution of transitive dependencies the build may fail, disregarding the fact, that the broken artifact is not even used, due to a newer matching version. I'm not sure if this applies here.

**Comment by akurtakov** [comment] 2022-06-15 13:16
It should pick the latest one AFAIK. There are things like mirror used by the build not synced yet, local artifact satisfying available, timeout period not passed before new check happens (-U helps here) and etc. Let's give it a bit more time .

**Comment by laeubi** [comment] 2022-06-15 13:23
> In previous situations I observed that Maven explores the entire tree of possible dependencies, i.e., all allowed versions. If one of them fails resolution of transitive dependencies the build may fail, disregarding the fact, that the broken artifact is not even used, due to a newer matching version. I'm not sure if this applies here.

Yep this happens here as one can easily check with running the example in an empty repository like this:

`mvn dependency:tree -X -Dmaven.repo.local=/tmp/repo`

**Comment by cdietrich** [comment] 2022-06-15 13:27
so this can be resolved only 
* by removing the bad artifact
* by adding the bad missing artifact as a stub/redirection etc
* avoiding any conflict working with explicit dependency exclude transitive

**Comment by laeubi** [comment] 2022-06-15 13:39
By the way, snippet to fix the problem could be like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>groupid</groupId>
	<artifactId>aid</artifactId>
	<version>1.0-SNAPSHOT</version>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.core.runtime</artifactId>
			<version>3.25.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.osgi.service</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
</project>
```

**Comment by vehovsky** [comment] 2022-06-15 14:01
@laeubi so everyone who ever used dependency on org.eclipse.core.runtime will have to do similar exclude or add org.eclipse.equinox.preferences under dependencyManagement in version that does work? Come on..

**Comment by vehovsky** [comment] 2022-06-15 14:24
@laeubi well Maven could be more graceful no doubt. But since it's not, it's time to admit this is ma major issue! Because even releasing a fixed version is not enough.

Thanks to your usage of version ranges many of our old releases are not repeatable. And we will be affected by this issue anytime we will need to release a patch.

The only solution that would not force anyone who ever used or will use org.eclipse.core.runtime dependency to do exclusions or any other shenanigans is to do what @ja6a-regnosys did, but deploy it to maven central.

```
<dependency>
    <groupId>org.osgi.service</groupId>
    <artifactId>org.osgi.service.prefs</artifactId>
    <version>1.1.2</version>
</dependency>
```

**Comment by cdietrich** [comment] 2022-06-15 14:32
@laeubi for sure not. but maybe we can beg the osgi project todo so

**Comment by vehovsky** [comment] 2022-06-15 14:39
> I don't think this will be allowed to deploy arbitrary content to central but who knows? Maybe it would be more suitable to ask the support to remove the offending versions from central, or do a relocation (not sure if this is supported by central) with a completely fresh release.

Agreed. Removal will work, anyone who has the artifact already cached in their local binary repo will have to remove it as well (plus devs will have to remove from local maven repos), but that is a minor issue.

**Comment by laeubi** [comment] 2022-06-15 14:46
> anyone who has the artifact already cached in their local binary repo will have to remove it as well

Not if the deploy a relocation pom pointing to the "fixed" version, this is not only possible for group-id changes as far as I can see:
https://maven.apache.org/ref/3.8.6/maven-model/maven.html#class_relocation

**Comment by alexlitovsky** [comment] 2022-06-15 17:42
I'm sorry, but for someone using these as transitive dependencies, and having made no changes to the application, what exactly is the fix now?  Because an application that used to build is all of a sudden not building.

**Comment by alexlitovsky** [comment] 2022-06-15 18:11
> @alexlitovsky I believe the fix or (current workaround) is this:
> 
>     * [Incorrect `org.osgi.service.prefs` dependency in org.eclipse.equinox.preferences-3.10.0 #54 (comment)](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1155979528)

Thank you for that, but that's not a fix and not a workable workaround.  Manually modifying the local .m2 repos on dozens of build nodes is not a workable solution for a serious product.

Come eclipse folks, please let us know how we can get our applications back into a working state.

**Comment by sravanlakkimsetti** [comment] 2022-06-15 18:25
> > @alexlitovsky I believe the fix or (current workaround) is this:
> > ```
> > * [Incorrect `org.osgi.service.prefs` dependency in org.eclipse.equinox.preferences-3.10.0 #54 (comment)](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1155979528)
> > ```
> 
> Thank you for that, but that's not a fix and not a workable workaround. Manually modifying the local .m2 repos on dozens of build nodes is not a workable solution for a serious product.
> 
> Come eclipse folks, please let us know how we can get our applications back into a working state.

We have deployed newer versions of the artifacts to maven. Please let us know how we can make maven to use latest versions during the build.

**Comment by vehovsky** [comment] 2022-06-15 18:47
@alexlitovsky one solution using exclude was offered by @laeubi [here](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1156487572) 

The other I mentioned [above](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1156514690) would leverage dependencyManagement, which I guess would be preferred for larger projects with transitive dependencies, which ideally import same BOM, so single change would fix the compilation for all your projects.

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.preferences</artifactId>
            <version>3.9.100</version>
        </dependency>
    </dependencies>
</dependencyManagement>
````

Still for me this is no more than **temporary workaround**. And I hope eclipse folks will contact maven central support and remove the broken release or deploy org.osgi.service.prefs under the [GAV](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1156519092) expected by the broken release.

**Comment by alexlitovsky** [comment] 2022-06-15 18:49
> @alexlitovsky one solution using exclude was offered by @laeubi [here](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1156487572)
> 
> The other I mentioned [above](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1156514690) would leverage dependencyManagement, which I guess would be preferred for larger projects with transitive dependencies, which ideally import same BOM, so single change would fix the compilation for all your projects.
> 
> ```
> <dependencyManagement>
>     <dependencies>
>         <dependency>
>             <groupId>org.eclipse.platform</groupId>
>             <artifactId>org.eclipse.equinox.preferences</artifactId>
>             <version>3.9.100</version>
>         </dependency>
>     </dependencies>
> </dependencyManagement>
> ```
> 
> Still for me this is no more than **temporary workaround**. And I hope eclipse folks will contact maven central support and remove the broken release or deploy org.osgi.service.prefs under the [GAV](https://github.com/eclipse-equinox/equinox.bundles/issues/54#issuecomment-1156519092) expected by the broken release.

Thanks @vehovsky .  We did fix this issue by uploading org.osgi.service.prefs under the wrong groupId to our mirror'd repo.

Hopefully this incident demonstrates why it's a terrible idea to use floating dependency versions.

**Comment by bjhargrave** [comment] 2022-06-15 19:08
> So how is OSGi planning to address this mistake?

OSGi made no mistake. OSGi has only ever used the `org.osgi` groupId for specification artifacts.

This mistake is entirely in Equinox which mis-generated GAV values for the OSGi artifacts during its build. So the problem is Equinox's to solve.

**Comment by jmini** [comment] 2022-06-15 20:51
> Hopefully this incident demonstrates why it's a terrible idea to use floating dependency versions.

As I wrote on [StackOverflow](https://stackoverflow.com/a/72626648) when you consume some dependencies using open version ranges, if you do not want to be disturbed by new releases (that can be corrupted as we saw today), you should fix/lock/control the versions you are using.

* Using a BOM file (I am maintaining one per Eclipse releases: [ECentral](https://jmini.github.io/ecentral/))
* Using a maven plugin such as [dependency-lock-maven-plugin](https://github.com/vandmo/dependency-lock-maven-plugin)

**Comment by mickaelistria** [comment] 2022-06-15 23:57
The root cause of the issue is not OSGi but Eclipse Platform generating wrong groupIds. https://github.com/eclipse-platform/eclipse.platform.releng/issues/50 covers what Eclipse Platform needs to change to avoid this problem in the future.
Please note that while it looks like a regression (X not working anymore), this issue is actually a consequence of a major improvement (Platform uses direct Maven artifacts without repackaging), which was not anticipated on some parts and thus causing temporary issues that are likely to have definitive fixes soon enough.

**Comment by mdaloia** [comment] 2022-06-16 02:55
What is it weird is that Maven tries to resolve all the versions on the range even when it could use the latest one available that matches the range. That is the reason why releasing a 3.10.1 wasn't enough for many of us. Maven downloads the `.pom` of all the versions including 3.10.0 and 3.10.1 but it first attempts to do some processing of 3.10.0 and because it is flawed fails the build and doesn't care that there is a new version that it could use (the one that fixed that mistake).

The explained above could be seen for example with:
```bash
wget https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.core.runtime/3.12.0/org.eclipse.core.runtime-3.12.0.pom
mvn -f org.eclipse.core.runtime-3.12.0.pom -Dmaven.repo.local=./temp-repo dependency:tree
```
Tested with 3.8.6

`org.eclipse.core.runtime-3.12.0.pom` has this dependency and version range:
```xml
<dependency>
    <groupId>org.eclipse.platform</groupId>
    <artifactId>org.eclipse.equinox.preferences</artifactId>
    <version>[3.4.0,4.0.0)</version>
</dependency>
```
Currently all the versions published on Maven Central matches that range...

![versions on Maven Central](https://user-images.githubusercontent.com/1738654/173976856-5b423940-deda-49e4-8dc0-0894f57a9add.png)

... so Maven downloads them all (just the pom... when a version is selected then that jar is downloaded).

![versions download to local repository](https://user-images.githubusercontent.com/1738654/173977136-ff5f01bd-5fad-4116-849d-5284ade39888.png)

After it fails, if you locally change what was wrong:
```bash
sed -i '' -e 's#<groupId>org.osgi.service</groupId>#<groupId>org.osgi</groupId>#g' ./temp-repo/org/eclipse/platform/org.eclipse.equinox.preferences/3.10.0/org.eclipse.equinox.preferences-3.10.0.pom
```
The build ends successfully.

Maybe there is an explanation of why Maven behave this way when ranges are used... or maybe it is a bug that didn't come up until now with this combination of factors.

So based on that, I think that to in order to transparently fix the issue for transitive consumers (i.e. not having everyone to modify build config that was working until now) would be one of 2 things:
- It is a Maven bug that gets fixed in the near future, or
- The GAV `org.eclipse.platform:org.eclipse.equinox.preferences:3.10.0` is removed from Maven Central (a practice not to follow but it is causing a lot of pain for end users and in the end it will be never used this version, so why keep it?).

**Comment by laeubi** [comment] 2022-06-16 03:09
> What is it weird is that Maven tries to resolve all the versions on the range even when it could use the latest one available that matches the range.

No this is not weird, this is required because maven could **not* just use the latest version, that's not what version ranges are for, this is especially to allow a **lower** version e.g. because of conflicts with other (transitive) dependencies or ones in your module, because of that maven first needs all the poms and all the transitive dependencies.

> Maybe there is an explanation of why Maven behave this way when ranges are used... or maybe it is a bug that didn't come up until now with this combination of factors.

As mentioned above, it might be god to create an enhancement request for maven to not fail completely but warn (as it does on other places, e.g. when it can't find the pom at all!).

**Comment by sravanlakkimsetti** [comment] 2022-06-16 04:47
Raised https://issues.sonatype.org/browse/OSSRH-81766 to get offending artifacts removed. Lets wait for maven central to act there

**Comment by tombrus** [comment] 2022-06-16 12:36
I hope you will be able to quickly release a fixed version. Thanks for all the open-source effort!
I thought I'll share my workaround:

You can patch your local .m2 cache with the following command (bash):
```
cp -r .m2/org/osgi/org.osgi.service.prefs/* .m2/org/osgi/service/org.osgi.service.prefs/
```
downside: it only works until you clean your .m2 cache! (but you can redo it or even script it)
upside: you do not need to think about removing it when a fixed version is published, nothing permanent is changed!

...and yes, if you have a zillion machines around it is not very practical to do it by hand... but you can script it... or make a cron job 😆 be creative!

**Comment by PranavPurwar** [comment] 2022-06-16 12:45
The fixed version was already released yesterday @tombrus

**Comment by bjhargrave** [comment] 2022-06-16 16:56
> `org.eclipse.core.runtime-3.12.0.pom` has this dependency and version range:
> 
> ```
> <dependency>
>     <groupId>org.eclipse.platform</groupId>
>     <artifactId>org.eclipse.equinox.preferences</artifactId>
>     <version>[3.4.0,4.0.0)</version>
> </dependency>
> ```

I will note that whatever code is generating the maven version range is generating a too-broad range. In the above example, the range includes `4`, `4.0`, 4.0.0-alpha` and other pre-final qualifiers on version `4.0.0`. The correct maven version range is `[3.4.0,4)` as that will include no version which starts with `4`.

**Comment by sravanlakkimsetti** [comment] 2022-06-17 03:14
> Raised https://issues.sonatype.org/browse/OSSRH-81766 to get offending artifacts removed. Lets wait for maven central to act there

the offending artifacts have been removed from maven central. Please try now

**Comment by adebiasi** [comment] 2022-06-17 07:06
Now I have the following error:
`Error injecting constructor, com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by akurtakov** [comment] 2022-06-17 07:14
Java SE 11 = class file version 55 . o.e.core.runtime bundle requires it since September 2021 release https://github.com/eclipse-platform/eclipse.platform.runtime/commit/74823fe0fcfe5f76baff2c29c93f0d8dbd9bcfe8

**Comment by adebiasi** [comment] 2022-06-17 07:23
Why this error didn't appear before the artifact's fix?

**Comment by cdietrich** [comment] 2022-06-17 07:32
@adebiasi can you provide a minimal reproducer

**Comment by akurtakov** [comment] 2022-06-17 07:32
> Why this error didn't appear before the artifact's fix?

This I can not even try to answer without reproducer and/or link to logs. Also please move to new issue for that.

**Comment by adebiasi** [comment] 2022-06-17 08:03
> > Why this error didn't appear before the artifact's fix?
> 
> This I can not even try to answer without reproducer and/or link to logs. Also please move to new issue for that.

I created https://github.com/eclipse-equinox/equinox.bundles/issues/61.

**Comment by laeubi** [comment] 2022-06-17 08:08
Platform requires java 11, so actually there is no "issue" and you probably have not seen it before because now the dependency has changed, the build was adjusted, using never java features of changed BREE, ...

If you require "old" behavior you have to use the old release...

**Comment by Borki** [comment] 2022-06-20 13:00
Can you let remove the wrong version also from JCenter:
https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.preferences

On maven central it's already removed.
